spring:
  application:
    name: mongle-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mongle
    username: postgres
    password: mongle123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080